export const JLPT_LEVELS = ['N5', 'N4', 'N3']; // N2 và N1 liên quan đến lộ trình chưa sử dụng nên tạm ẩn để đồng bộ với Mobile.

// Nhãn chỉ dùng cho giao diện; giữ BEGINNER để tương thích ngược với tài khoản cũ.
export const JLPT_LEVEL_LABELS = {
  BEGINNER: 'Mới bắt đầu',
  N5: 'N5',
  N4: 'N4',
  N3: 'N3',
  N2: 'N2',
  N1: 'N1',
};

// Axios phát sự kiện này khi backend trả 401 để AuthProvider cập nhật lại UI.
export const AUTH_UNAUTHORIZED_EVENT = 'auth:unauthorized';

// Axios phát sự kiện sau khi refresh token thành công để AuthContext nhận access
// token và user mới mà không cần tải lại trang.
export const AUTH_SESSION_REFRESHED_EVENT = 'auth:session-refreshed';

// Các bản dịch cho luồng xác thực (Login, Register, ResetPassword, ConfirmResetPassword)
export const AUTH_TRANSLATIONS = {
  vi: {
    backToHome: 'Trang chủ',
    login: {
      title: 'Chào mừng trở lại',
      subtitle: 'Tiếp tục hành trình tiếng Nhật của bạn với JELA.',
      emailLabel: 'Email',
      passwordLabel: 'Mật khẩu',
      forgotPasswordLink: 'Quên mật khẩu?',
      rememberLabel: 'Lưu tài khoản và mật khẩu',
      rememberSmall: 'Chỉ nên bật trên thiết bị cá nhân.',
      loginButton: 'Đăng nhập',
      loggingIn: 'Đang đăng nhập...',
      orDivider: 'Hoặc',
      googleButton: 'Tiếp tục với Google',
      connectingGoogle: 'Đang kết nối...',
      noAccount: 'Chưa có tài khoản?',
      registerLink: 'Đăng ký',
      toastSuccess: 'Đăng nhập thành công!',
      toastLocked: 'Tài khoản của bạn đã bị khóa',
      toastFailed: 'Email hoặc mật khẩu không đúng',
      toastError: 'Không thể kết nối máy chủ. Vui lòng thử lại',
      googleFailed: 'Đăng nhập Google thất bại',
      googleTokenError: 'Token không hợp lệ. Vui lòng thử lại.',
    },
    register: {
      title: 'Tạo tài khoản',
      subtitle: 'Bắt đầu hành trình chinh phục N3 ngay hôm nay.',
      fullNameLabel: 'Họ và tên',
      fullNameHelper: 'Họ và tên từ 2 đến 50 ký tự, không chứa số và ký tự đặc biệt.',
      emailLabel: 'Email',
      emailHelper: 'Địa chỉ email hợp lệ (ví dụ: nguyenvana@email.com).',
      passwordLabel: 'Mật khẩu',
      passwordHelper: 'Yêu cầu mật khẩu:',
      passCriteriaLength: 'Từ 8 đến 32 ký tự',
      passCriteriaUpper: 'Chữ hoa (A-Z)',
      passCriteriaLower: 'Chữ thường (a-z)',
      passCriteriaNumber: 'Chữ số (0-9)',
      levelLabel: 'Trình độ tiếng Nhật hiện tại',
      registerButton: 'Tạo tài khoản',
      registering: 'Đang tạo tài khoản...',
      hasAccount: 'Đã có tài khoản?',
      loginLink: 'Đăng nhập',
      legalText: 'Bằng đăng ký, bạn đồng ý với {terms} và {privacy} của JELA.',
      termsLink: 'Điều khoản dịch vụ',
      privacyLink: 'Chính sách bảo mật',
      toastSuccess: 'Đăng ký tài khoản thành công!',
      toastServerError: 'Hệ thống đang bận hoặc gặp sự cố, vui lòng thử lại sau nhé!',
      toastEmailConflict: 'Email này đã được đăng ký.',
      toastError: 'Đã có lỗi xảy ra. Vui lòng thử lại.',
      regClosedTitle: 'Đăng ký tài khoản hiện đang tạm khóa',
      regClosedSub: 'Quản trị viên đã tạm tắt tính năng đăng ký thành viên mới. Vui lòng quay lại sau!',
    },
    forgot: {
      title: 'Quên mật khẩu',
      subtitle: 'Nhập địa chỉ email của bạn và chúng tôi sẽ gửi link để đặt lại mật khẩu.',
      emailLabel: 'Email',
      sendButton: 'Gửi link đặt lại',
      sending: 'Đang gửi yêu cầu...',
      backToLogin: 'Quay lại đăng nhập',
      toastSuccess: 'Nếu email tồn tại, hướng dẫn đặt lại mật khẩu sẽ được gửi đến bạn.',
      toastError: 'Không thể gửi yêu cầu lúc này. Vui lòng thử lại sau.',
    },
    confirmReset: {
      title: 'Đặt lại mật khẩu',
      subtitle: 'Nhập mã xác nhận và mật khẩu mới cho tài khoản của bạn.',
      tokenLabel: 'Mã xác nhận (Token)',
      tokenPlaceholder: 'Dán mã token từ email của bạn vào đây',
      newPasswordLabel: 'Mật khẩu mới',
      confirmPasswordLabel: 'Xác nhận mật khẩu mới',
      submitButton: 'Xác nhận',
      submitting: 'Đang xử lý...',
      backToLogin: 'Quay lại trang Đăng nhập',
      toastSuccess: 'Đặt lại mật khẩu thành công!',
      toastInvalidToken: 'Mã xác nhận không hợp lệ hoặc đã hết hạn.',
      toastError: 'Đã xảy ra lỗi. Vui lòng thử lại.',
    }
  },
  en: {
    backToHome: 'Home',
    login: {
      title: 'Welcome Back',
      subtitle: 'Continue your Japanese journey with JELA.',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      forgotPasswordLink: 'Forgot password?',
      rememberLabel: 'Remember account & password',
      rememberSmall: 'Only enable on personal devices.',
      loginButton: 'Login',
      loggingIn: 'Logging in...',
      orDivider: 'Or',
      googleButton: 'Continue with Google',
      connectingGoogle: 'Connecting...',
      noAccount: "Don't have an account?",
      registerLink: 'Sign Up',
      toastSuccess: 'Login successful!',
      toastLocked: 'Your account has been locked',
      toastFailed: 'Incorrect email or password',
      toastError: 'Failed to connect to the server. Please try again',
      googleFailed: 'Google Login failed',
      googleTokenError: 'Invalid token. Please try again.',
    },
    register: {
      title: 'Create Account',
      subtitle: 'Start your journey to conquer N3 today.',
      fullNameLabel: 'Full Name',
      fullNameHelper: 'Name between 2 and 50 characters, no numbers or special characters.',
      emailLabel: 'Email',
      emailHelper: 'Valid email address (e.g. name@example.com).',
      passwordLabel: 'Password',
      passwordHelper: 'Password requirements:',
      passCriteriaLength: '8 to 32 characters',
      passCriteriaUpper: 'Uppercase (A-Z)',
      passCriteriaLower: 'Lowercase (a-z)',
      passCriteriaNumber: 'Number (0-9)',
      levelLabel: 'Current Japanese Level',
      registerButton: 'Create Account',
      registering: 'Creating account...',
      hasAccount: 'Already have an account?',
      loginLink: 'Login',
      legalText: 'By registering, you agree to our {terms} and {privacy}.',
      termsLink: 'Terms of Service',
      privacyLink: 'Privacy Policy',
      toastSuccess: 'Account registered successfully!',
      toastServerError: 'System is busy or has an issue, please try again later!',
      toastEmailConflict: 'This email is already registered.',
      toastError: 'An error occurred. Please try again.',
      regClosedTitle: 'Registration is temporarily locked',
      regClosedSub: 'Admin has temporarily disabled new registrations. Please come back later!',
    },
    forgot: {
      title: 'Forgot Password',
      subtitle: 'Enter your email address and we will send a password reset link.',
      emailLabel: 'Email',
      sendButton: 'Send Reset Link',
      sending: 'Sending...',
      backToLogin: 'Back to Login',
      toastSuccess: 'If the email exists, instructions to reset password will be sent to you.',
      toastError: 'Cannot send request now. Please try again later.',
    },
    confirmReset: {
      title: 'Reset Password',
      subtitle: 'Enter the verification code and your new password.',
      tokenLabel: 'Verification Code (Token)',
      tokenPlaceholder: 'Paste token from your email here',
      newPasswordLabel: 'New Password',
      confirmPasswordLabel: 'Confirm New Password',
      submitButton: 'Confirm',
      submitting: 'Processing...',
      backToLogin: 'Back to Login Page',
      toastSuccess: 'Password reset successful!',
      toastInvalidToken: 'Invalid or expired verification code.',
      toastError: 'An error occurred. Please try again.',
    }
  }
};
