export const FOCUS_STUDY_TRANSLATIONS = {
  vi: {
    close: 'Đóng chế độ tập trung',
    lessonProgress: 'Tiến độ bài học',
    cardCount: (current, total) => `${current} / ${total} thẻ`,
    streak: (days) => `Chuỗi ${days} ngày`,
    flipHint: 'Chạm để lật',
    flipCard: 'Lật thẻ Kanji để xem đáp án',
    meaning: 'Nghĩa',
    onyomi: 'Âm On',
    kunyomi: 'Âm Kun',
    needsReview: 'Cần ôn lại',
    remembered: 'Đã nhớ',
    completedTitle: 'Hoàn thành phiên học!',
    completedDescription: 'Bạn đã xem hết các thẻ Kanji trong phiên này.',
    rememberedResult: 'Đã nhớ',
    reviewResult: 'Cần ôn lại',
    studyAgain: 'Học lại',
    finish: 'Hoàn tất',
    emptyTitle: 'Chưa có thẻ để học',
    emptyDescription: 'Hãy chọn một cấp độ có Kanji rồi bắt đầu lại.',
  },
  en: {
    close: 'Close focus mode',
    lessonProgress: 'Lesson progress',
    cardCount: (current, total) => `${current} / ${total} cards`,
    streak: (days) => `${days}-day streak`,
    flipHint: 'Tap to flip',
    flipCard: 'Flip the Kanji card to reveal the answer',
    meaning: 'Meaning',
    onyomi: 'On reading',
    kunyomi: 'Kun reading',
    needsReview: 'Review again',
    remembered: 'Remembered',
    completedTitle: 'Study session complete!',
    completedDescription: 'You have reviewed every Kanji card in this session.',
    rememberedResult: 'Remembered',
    reviewResult: 'Review again',
    studyAgain: 'Study again',
    finish: 'Finish',
    emptyTitle: 'No cards to study',
    emptyDescription: 'Choose a level containing Kanji and start again.',
  },
};
