export const SETTINGS_TRANSLATIONS = {
  vi: {
    pageTitle: 'Cài đặt',
    accountStatus: 'Trạng thái tài khoản',
    registeredEmail: 'Email đã đăng ký',
    verified: 'Đã xác minh',
    unverified: 'Chưa xác minh',
    status: 'Trạng thái',
    checkingEmailStatus: 'Đang kiểm tra',
    editEmail: 'Chỉnh sửa email',
    sendVerificationEmail: 'Gửi email xác minh',
    verifyEmailTitle: 'Xác minh địa chỉ email',
    verifyEmailDescription:
      'JELA sẽ gửi liên kết xác minh đến địa chỉ email đã đăng ký bên dưới.',
    editEmailTitle: 'Chỉnh sửa email',
    editEmailDescription:
      'Nhập địa chỉ email mới. Bạn cần xác minh email mới trước khi sử dụng đầy đủ các chức năng tài khoản.',
    newEmail: 'Địa chỉ email mới',
    continueEditEmail: 'Cập nhật email',
    processing: 'Đang xử lý...',
    emailRequired: 'Vui lòng nhập địa chỉ email.',
    emailInvalid: 'Địa chỉ email không đúng định dạng.',
    emailMustBeDifferent: 'Email mới phải khác email hiện tại.',
    verificationEmailSent: 'Email xác minh đã được gửi. Vui lòng kiểm tra hộp thư.',
    verificationEmailFailed: 'Không thể gửi email xác minh. Vui lòng thử lại.',
    emailUpdated:
      'Email đã được cập nhật. Vui lòng kiểm tra hộp thư để xác minh địa chỉ mới.',
    emailUpdateFailed: 'Không thể cập nhật email. Vui lòng thử lại.',
    emailVerificationApiMissing:
      'API gửi email xác minh chưa sẵn sàng. Hãy bật emailVerification trong apiConfig.js sau khi backend hoàn thiện.',
    emailUpdateApiMissing:
      'API đổi email chưa sẵn sàng. Hãy bật emailUpdate trong apiConfig.js sau khi backend hoàn thiện.',
    externalEmailNote:
      'Email được quản lý bởi nhà cung cấp đăng nhập bên thứ ba nên không thể chỉnh sửa tại JELA.',
    localEmailNote: 'Bạn sẽ cần xác minh lại địa chỉ email mới sau khi thay đổi.',
    security: 'Bảo mật',
    securityDescription: 'Bảo vệ tài khoản bằng cách cập nhật mật khẩu định kỳ.',
    lastChanged: 'Nên sử dụng mật khẩu mạnh và cập nhật định kỳ để bảo vệ tài khoản.',
    externalPasswordNote:
      'Mật khẩu được quản lý bởi nhà cung cấp đăng nhập của bạn và không thể đổi tại JELA.',
    googlePasswordBlocked:
      'Tài khoản này đăng nhập bằng Google nên không thể đổi mật khẩu trong ứng dụng.',
    checkingAccountType: 'Đang xác định loại tài khoản...',
    changePassword: 'Đổi mật khẩu',
    changePasswordTitle: 'Đổi mật khẩu',
    changePasswordDescription:
      'Nhập mật khẩu hiện tại và tạo mật khẩu mới để bảo vệ tài khoản của bạn.',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmNewPassword: 'Xác nhận mật khẩu mới',
    passwordPlaceholder: 'Nhập mật khẩu',
    passwordRequirements: 'Mật khẩu mới phải có:',
    passwordRuleLength: 'Từ 8 đến 32 ký tự',
    passwordRuleUppercase: 'Ít nhất 1 chữ hoa',
    passwordRuleLowercase: 'Ít nhất 1 chữ thường',
    passwordRuleNumber: 'Ít nhất 1 chữ số',
    passwordRuleSpecial: 'Ít nhất 1 ký tự đặc biệt',
    passwordRuleNoWhitespace: 'Không chứa khoảng trắng',
    currentPasswordRequired: 'Vui lòng nhập mật khẩu hiện tại.',
    newPasswordRequired: 'Vui lòng nhập mật khẩu mới.',
    newPasswordInvalid: 'Mật khẩu mới chưa đáp ứng đầy đủ các yêu cầu.',
    passwordMustBeDifferent: 'Mật khẩu mới phải khác mật khẩu hiện tại.',
    confirmPasswordRequired: 'Vui lòng xác nhận mật khẩu mới.',
    passwordMismatch: 'Mật khẩu xác nhận không khớp.',
    cancel: 'Hủy',
    close: 'Đóng',
    updatePassword: 'Cập nhật mật khẩu',
    updatingPassword: 'Đang cập nhật...',
    passwordChanged: 'Đổi mật khẩu thành công',
    passwordChangeFailed: 'Đổi mật khẩu thất bại. Vui lòng thử lại.',
    currentPasswordIncorrect: 'Mật khẩu hiện tại không chính xác.',
    passwordRateLimited: 'Bạn thao tác quá nhiều lần. Vui lòng thử lại sau.',
    changePasswordApiMissing:
      'API đổi mật khẩu chưa sẵn sàng. Hãy bật changePassword trong apiConfig.js sau khi backend hoàn thiện.',
    preferences: 'Giao diện & tùy chọn',
    darkMode: 'Chế độ tối',
    appLanguage: 'Ngôn ngữ ứng dụng',
    notifications: 'Thông báo',
    emailNotifications: 'Thông báo qua email',
    emailNotificationsDescription: 'Nhận báo cáo tiến độ và thông báo quan trọng.',
    streakReminders: 'Nhắc nhở chuỗi học tập',
    streakRemindersDescription: 'Nhắc bạn học mỗi ngày để duy trì chuỗi.',
    signOut: 'Đăng xuất',
    comingSoon: 'Tính năng này đang được phát triển.',
    notificationSaved: 'Đã lưu tùy chọn thông báo trên thiết bị này.',
  },
  en: {
    pageTitle: 'Settings',
    accountStatus: 'Account Status',
    registeredEmail: 'Registered Email',
    verified: 'Verified',
    unverified: 'Unverified',
    status: 'Status',
    checkingEmailStatus: 'Checking',
    editEmail: 'Edit email',
    sendVerificationEmail: 'Send Verification Email',
    verifyEmailTitle: 'Verify Email Address',
    verifyEmailDescription:
      'JELA will send a verification link to the registered email address below.',
    editEmailTitle: 'Edit Email',
    editEmailDescription:
      'Enter a new email address. You must verify it before using all account features.',
    newEmail: 'New email address',
    continueEditEmail: 'Update Email',
    processing: 'Processing...',
    emailRequired: 'Please enter an email address.',
    emailInvalid: 'Please enter a valid email address.',
    emailMustBeDifferent: 'The new email must differ from the current email.',
    verificationEmailSent: 'Verification email sent. Please check your inbox.',
    verificationEmailFailed: 'Unable to send the verification email. Please try again.',
    emailUpdated: 'Email updated. Please check your inbox to verify the new address.',
    emailUpdateFailed: 'Unable to update the email. Please try again.',
    emailVerificationApiMissing:
      'The email verification API is unavailable. Enable emailVerification in apiConfig.js when the backend is ready.',
    emailUpdateApiMissing:
      'The email update API is unavailable. Enable emailUpdate in apiConfig.js when the backend is ready.',
    externalEmailNote:
      'This email is managed by your third-party sign-in provider and cannot be edited in JELA.',
    localEmailNote: 'You will need to verify the new email address after changing it.',
    security: 'Security',
    securityDescription: 'Protect your account by updating your password regularly.',
    lastChanged: 'Use a strong password and update it periodically to protect your account.',
    externalPasswordNote:
      'Your password is managed by your sign-in provider and cannot be changed in JELA.',
    googlePasswordBlocked:
      'This account signs in with Google, so its password cannot be changed in the app.',
    checkingAccountType: 'Checking account type...',
    changePassword: 'Change Password',
    changePasswordTitle: 'Change Password',
    changePasswordDescription:
      'Enter your current password and create a new one to keep your account secure.',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    passwordPlaceholder: 'Enter password',
    passwordRequirements: 'The new password must contain:',
    passwordRuleLength: '8 to 32 characters',
    passwordRuleUppercase: 'At least 1 uppercase letter',
    passwordRuleLowercase: 'At least 1 lowercase letter',
    passwordRuleNumber: 'At least 1 number',
    passwordRuleSpecial: 'At least 1 special character',
    passwordRuleNoWhitespace: 'No whitespace',
    currentPasswordRequired: 'Please enter your current password.',
    newPasswordRequired: 'Please enter a new password.',
    newPasswordInvalid: 'The new password does not meet all requirements.',
    passwordMustBeDifferent: 'The new password must differ from the current password.',
    confirmPasswordRequired: 'Please confirm your new password.',
    passwordMismatch: 'The confirmation password does not match.',
    cancel: 'Cancel',
    close: 'Close',
    updatePassword: 'Update Password',
    updatingPassword: 'Updating...',
    passwordChanged: 'Password changed successfully',
    passwordChangeFailed: 'Password change failed. Please try again.',
    currentPasswordIncorrect: 'The current password is incorrect.',
    passwordRateLimited: 'Too many attempts. Please try again later.',
    changePasswordApiMissing:
      'The change password API is unavailable. Enable changePassword in apiConfig.js when the backend is ready.',
    preferences: 'Appearance & Preferences',
    darkMode: 'Dark Mode',
    appLanguage: 'App Language',
    notifications: 'Notifications',
    emailNotifications: 'Email Notifications',
    emailNotificationsDescription: 'Receive progress reports and important announcements.',
    streakReminders: 'Daily Streak Reminders',
    streakRemindersDescription: 'Get reminded to keep your learning streak active.',
    signOut: 'Sign Out',
    comingSoon: 'This feature is currently under development.',
    notificationSaved: 'Notification preference saved on this device.',
  },
};

export const SETTINGS_NOTIFICATION_KEYS = {
  email: 'jelaEmailNotifications',
  streak: 'jelaStreakReminders',
};

export const SHARED_APP_TRANSLATIONS = {
  vi: {
    learner: 'Học viên JELA',
    level: 'Cấp',
    profile: 'Thông tin cá nhân',
    settings: 'Cài đặt',
    signOut: 'Đăng xuất',
    signedOut: 'Đăng xuất thành công.',
    navigation: 'Điều hướng chính',
    mobileNavigation: 'Điều hướng di động',
    startLesson: 'BẮT ĐẦU BÀI HỌC',
    landingTitle: 'Trang giới thiệu',
    studentSpace: 'Trang học viên',
    adminPage: 'Trang quản trị',
    landingPage: 'Trang chủ',
    nav: {
      '/': 'Tổng quan',
      '/roadmap': 'Lộ trình',
      '/dictionary': 'Từ điển',
      '/kanji': 'Hán tự',
      '/my-decks': 'Danh sách học',
    },
  },
  en: {
    learner: 'JELA Learner',
    level: 'Level',
    profile: 'Personal Information',
    settings: 'Settings',
    signOut: 'Sign Out',
    signedOut: 'Signed out successfully.',
    navigation: 'Main navigation',
    mobileNavigation: 'Mobile navigation',
    startLesson: 'START LESSON',
    landingTitle: 'About Us',
    studentSpace: 'Student Page',
    adminPage: 'Admin Page',
    landingPage: 'Home',
    nav: {
      '/': 'Dashboard',
      '/roadmap': 'Roadmap',
      '/dictionary': 'Dictionary',
      '/kanji': 'Kanji Library',
      '/my-decks': 'My Decks',
    },
  },
};
